---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
  fixme:
    enabled: true
  rubocop:
    enabled: true

ratings:
   paths:
     - "**"

exclude_paths:
  - lib/firebase-ruby/trollop.rb
