---
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
  fixme:
    enabled: true
  rubocop:
    enabled: true

exclude_paths:
  - lib/firebase-ruby/trollop.rb
